# .github/workflows/deploy-ec2.yml
name: Deploy Backend to EC2

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Repository name to deploy"
        required: true
        type: string
      host:
        description: "EC2 public IP or hostname"
        required: true
        type: string
      port:
        description: "Port to expose from container"
        required: false
        default: "5000"
        type: string
    secrets:
      EC2_SSH_KEY:
        description: "Private SSH key for EC2 access"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ inputs.host }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # Install git and docker if not already installed
            sudo yum update -y
            sudo yum install -y git docker

            # start docker service
            sudo service docker start

            # allow ec2-user to run docker without sudo
            sudo usermod -aG docker ec2-user || true

            # pull or clone repo
            REPO_NAME="${{ inputs.repo_name }}"
            if [ ! -d "$REPO_NAME" ]; then
                git clone https://github.com/jegansekar112/${REPO_NAME}.git $REPO_NAME
            fi
            cd $REPO_NAME
            git pull origin main

            # build and run docker
            docker build -t $REPO_NAME .
            docker stop $REPO_NAME || true
            docker rm $REPO_NAME || true
            docker run -d --name $REPO_NAME -p ${{ inputs.port }}:${{ inputs.port }} $REPO_NAME
